<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OV165R3" failures="2" tests="6" name="chrome" time="152.645" errors="0" timestamp="2025-07-31T22:52:06 IST">
  <testcase classname="com.tests.LoginTest" name="websiteCheck" time="51.104">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.tests.LoginTest.websiteCheck(LoginTest.java:101)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- websiteCheck -->
  <testcase classname="com.tests.LoginTest" name="search" time="5.022"/>
  <testcase classname="com.tests.LoginTest" name="addToWishList" time="19.98"/>
  <testcase classname="com.tests.LoginTest" name="addToCart" time="24.236"/>
  <testcase classname="com.tests.LoginTest" name="placeOrder" time="6.771"/>
  <testcase classname="com.tests.LoginTest" name="checkDelivery" time="20.794">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.tests.LoginTest.checkDelivery(LoginTest.java:501)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- checkDelivery -->
</testsuite> <!-- chrome -->
